on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
        python -m pip install --quiet --upgrade pip
        pip install --quiet pre-commit
    - name: Run pre-commit
      run: |
        pre-commit run --all
