on:
  workflow_dispatch:
  # every day at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Publish to github pages
      run: |
        rm -rf gh-pages/*
        touch gh-pages/.nojekyll
        mkdir -p gh-pages/meeting-notes
        cd gh-pages

        curl -s -L -o meeting-notes/cross-tab.pdf https://docs.google.com/document/d/1CQ7gqc9wgFecLY7x81Y2l363zSykHNkqERg4_2sbgQs/export?format=pdf

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        # Ignore errors because no updates returns an error status.
        git commit --reset-author --amend -m "Update from github actions"
        git push --force origin gh-pages
